args: !!python/object:argparse.Namespace
  add_name: ''
  batch_size: 128
  clip: 5
  dataset: rounD
  dry_run: false
  epochs: 200
  gnn_layer: natt
  hidden_size: 128
  init_static: false
  log_interval: 100
  lr: 0.0001
  motion_model: neuralode
  n_gnn_layers: 1
  n_heads: 1
  n_mixtures: 8
  n_ode_hidden: 16
  n_ode_layers: 1
  n_ode_static: false
  n_workers: 8
  ode_solver: rk4
  overwrite_data: false
  seed: 1234
  small_ds: false
  sparse: false
  store_data: true
  teacher_forcing: 0.2
  tune_batch_size: false
  tune_lr: false
  u1_lim: 10
  u2_lim: 10
  use_cuda: true
  use_edge_features: true
  use_logger: false
